### ISSUE TITLE
Refactoring: Simplify the demo and tutorial

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/shop-demo#19]
As a first introductory demo application the ShopDemo is a little bit to complex. Especially the integration of PouchDB is hard to grasp for a beginner and introduces unnecessary complexity into a tutorial for LaxarJS.

**Comment by x1B** [comment]
Branch: `feature/19-reducing-complexity`

**Comment by x1B** [comment]
@jonaswjs: moving the issue to you for updating the graphical diagrams

**Comment by jonaswjs** [comment]
@d-voss: moving the issue to you for revising the CSS

**Comment by d-voss** [comment]
Implemented on `master` (`v1.9.0`)
