### ISSUE TITLE
documentation: consider Windows specific "path"-handling for grunt-init commands

### ISSUE THREAD

**Issue by mkemmann** [LaxarJS/shop-demo#26]
According to the grunt-init documentation (http://gruntjs.com/project-scaffolding) you have to use "%USERPROFILE%\.grunt-init\" instead of  "~/.grunt-init/" if you work with windows. This should be mentioned in the "Getting started" tutorial ("Get the Prerequisites" & "Creating a LaxarJS Application from the Template") of the shop demo.

**Comment by x1B** [comment]
Fixed on `master` (`v1.10.0`) and `release-1.9.x` (`v1.9.1`).
