### ISSUE TITLE
Suggestion: Nightwatch-tests and Saucelabs.

### ISSUE THREAD

**Issue by qacwnfq** [LaxarJS/shop-demo#46]
The shop-demo branch master-2.x should use Saucelabs and Nightwatch to ensure it still works with the new changes.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

Already through Travis-CI: https://travis-ci.org/LaxarJS/shop-demo/builds/221745425
(browser: sauce)

@qacwnfq thanks for the PR
