### ISSUE TITLE
tutorial: add missing graphics

### ISSUE THREAD

**Issue by x1B** [LaxarJS/shop-demo#49]
- [x] The tutorial still contains 4 TODO items (in comments), where diagrams/graphics are missing.
- [x] Additionally, [step7.png](https://github.com/LaxarJS/shop-demo/blob/8c8c229/docs/tutorials/img/step7.png) should be redone, because it shows outdated widget IDs.

**Comment by jonaswjs** [comment]
@x1B : Please review the changes on branch feature/49-add-missing-graphics

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
