### ISSUE TITLE
documentation: add missing hints

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/shop-demo#51]
- In step 3 a hint about the webpack configuration for the sass-loader is missing.
- Fix page configuration of shopping-cart-widget
- Fix link in step 8
- Update dependencies

**Comment by jonaswjs** [comment]
@x1B : Please review the changes on branch feature/49-add-missing-graphics

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
