### ISSUE TITLE
tutorial: typos

### ISSUE THREAD

**Issue by qacwnfq** [LaxarJS/shop-demo#52]
In 07: 
- In the vue-template: The form has property @submit="filter()"  at first and later @submit="search()". This is a bit confusing
- In the vue-controller: The articles are filtered for "some", instead of "name"

In 08:
- Mention also replacing theme in init.js  create(...).tooling.

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`).

@qacwnfq thanks for the report
