### ISSUE TITLE
404 for font in debug mode

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/shop-demo#57]
After the changes of (#56) in debug mode the browser can't load the font awesome.

Hint:
https://github.com/bholloway/resolve-url-loader#source-maps-required

https://github.com/bholloway/resolve-url-loader/issues/25

**Comment by x1B** [comment]
Apperently, we don't need the resolve-url-loader if we just use the ExtractTextPlugin, like for production. I guess it's probably slower, but it should work :)

**Comment by x1B** [comment]
Fixed on `master-2.x` (`v2.0.0`)
