### ISSUE TITLE
Fix & re-enable saucelabs build

### ISSUE THREAD

**Issue by x1B** [LaxarJS/shop-demo#66]
The saucelabs build has been disabled. Regular builds seem to be working -- We'll need to check what needs to be done to fix this.

**Comment by qacwnfq** [comment]
My conjecture is that the no-ssl-bump-profile is broken, due to the update to the sauce-labs tunnel.
We don't need the no-ssl-bump-profile if we don't test Android 4. It was just a workaround.

I can image that sauce disallowed no-ssl-bump on their side due to security reasons.

**Comment by qacwnfq** [comment]
Fixed sauce labs by removing no-ssl-bump tunnel.
